name: Setup Kali Linux RDP

on: push

jobs:
  setup-kali:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Kali Linux and RDP
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo docker pull danielguerra/ubuntu-xrdp:latest
        sudo docker run -d -p 3389:3389 danielguerra/ubuntu-xrdp:latest
        echo "Username: ubuntu"
        echo "Password: ubuntu"
        echo "RDP Address: $(curl -s ifconfig.me):3389"
