name: Setup Kali Linux RDP

on: push

jobs:
  setup-kali:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce
        sudo systemctl start docker

    - name: Install and Run Kali Linux RDP
      run: |
        sudo docker pull danielguerra/ubuntu-xrdp:latest
        sudo docker run -d -p 3389:3389 danielguerra/ubuntu-xrdp:latest
        echo "Username: ubuntu"
        echo "Password: ubuntu"
        echo "RDP Address: $(curl -s ifconfig.me):3389"
